### ISSUE TITLE
[Compatability] When Collective is installed, lightning entities from channeling tridents crash the game

### ISSUE THREAD

**Issue by Toastberries** [CammiesCorner/Armaments#1]
This happens whether it's raining or thundering, and as far as I can tell only when the lightning is summoned from a channeling trident.

MC version: 1.20.1
Quilt version: 0.25.0

**Mod list:**
- Armaments | 1.0+1.20.1
- Cardinal Components API | 5.2.2
- [Collective | 7.60](https://modrinth.com/mod/collective/version/1.20.1-7.60-fabric+forge+neo)
- Quilted Fabric API | 7.5.0+0.91.0-1.20.1
- Sparkweave Engine | 0.4.1

[Crash report](https://github.com/CammiePone/Armaments/files/15444345/channeling.crash.with.collective-crash-report.txt)

**Comment by CammiePone** [comment]
just uploaded a new version to both cf and modrinth, should fix the issue
