### ISSUE TITLE
Armaments somehow removes i-frames for all LivingEntities

### ISSUE THREAD

**Issue by unilock** [CammiesCorner/Armaments#3]
With Armaments installed, i-frames for all LivingEntities are completely disabled - the time between when a LivingEntity takes damage and the soonest it can take damage again is always 0.

This can be seen by entering survival mode and jumping in lava - you'll take the full amount of damage *every tick* instead of once every 10 ticks or so.

I suspect the issue is here, somewhere:

https://github.com/CammiePone/Armaments/blob/18a3d53d44c824e39f706a85a5aaeea71141eb1f/src/main/java/dev/cammiescorner/armaments/mixin/LivingEntityMixin.java#L58-L67

**Comment by CammiePone** [comment]
oh im dumb. never saw this report

yeah, I'm pretty sure you're right. we kinda came across this in a server my partner is running, since i only recently got back into being able to make mods. im gonna try and push a fix tonight

**Comment by CammiePone** [comment]
fixeded it, sorry it took so long
